#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# running export scripts
npm run export:md

# adding exported files
git add README.md
git add RESUME.md
git add CV.md

# commit them to the last commit
git commit --amend