#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# running export scripts
npm run export:md

# adding exported files
git add *.md

# commit them to the last commit
if [[ `git status --porcelain` ]]; then
  git commit -m "📃 Markdown files auto exported"
fi